defmodule KiwiCodec.RustlerGenerator do
  @moduledoc """
  Generates Rustler decoder code from Kiwi schemas for RustQ manifests.

  This is an experimental bridge for optional native backends. It generates a
  complete Rust source file for schema-dependent decoder functions and NIF
  entrypoints; `rustq.exs` owns writing and freshness checks.

  The generated source includes the Rustler imports, RustQ Rustler term helpers,
  schema decoders, and requested entrypoints. The caller only needs to provide a
  `Decoder<'a>` type with Kiwi primitive reader methods.
  """

  alias KiwiCodec.RustlerGenerator.Definition
  alias KiwiCodec.RustlerGenerator.Entrypoint
  alias KiwiCodec.RustlerGenerator.Selection
  alias KiwiCodec.RustlerGenerator.Splice
  alias KiwiCodec.Schema
  alias RustQ.Rust

  @type entrypoint :: Entrypoint.entrypoint()

  @doc """
  Returns a complete Rust source file for generated Rustler decoders.

      generate :native_decoders, "native/my_nif/src/generated.rs" do
        schema = KiwiCodec.parse_schema!(File.read!("priv/schema.kiwi"))

        content KiwiCodec.RustlerGenerator.source(schema,
          definitions: ["Node"],
          entrypoints: [decode_node: "Node"],
          module_prefix: "Example.Schema"
        )
      end

  Options:

    * `:definitions` - schema definition names to generate, including their
      dependencies. Defaults to all definitions.
    * `:entrypoints` - `{nif_name, definition_name}` entries for generated NIFs.
    * `:module_prefix` - Elixir module prefix for decoded structs.
    * `:decoder` - Rust path imported as `Decoder`. Defaults to
      `"crate::runtime::Decoder"`.

  """
  @spec source(Schema.t(), keyword()) :: String.t()
  def source(%Schema{} = schema, opts) do
    [source_header(opts), generated_fragments(schema, opts)]
    |> List.flatten()
    |> Enum.map_join("\n\n", &Rust.to_fragment/1)
    |> Kernel.<>("\n")
  end

  defp generated_fragments(%Schema{} = schema, opts) do
    definitions = Keyword.get(opts, :definitions, [])
    entrypoints = Keyword.get(opts, :entrypoints, [])
    module_prefix = Keyword.fetch!(opts, :module_prefix)

    definition_map = Selection.definition_map(schema)
    selected = Selection.definitions(schema, definitions, definition_map)

    [
      Splice.rustler_helpers(),
      Definition.fragments(selected, module_prefix, definition_map),
      Entrypoint.fragments(entrypoints)
    ]
  end

  defp source_header(opts) do
    decoder = Keyword.get(opts, :decoder, "crate::runtime::Decoder")

    """
    // This file is generated by KiwiCodec and RustQ. Do not edit by hand.
    #[allow(dead_code)]

    use rustler::types::atom::Atom;
    use rustler::{Binary, Encoder, Env, Error, NifResult, Term};
    use std::sync::OnceLock;

    use #{decoder};
    """
  end
end
